name: theme_extension
description: A new Flutter package project.
homepage: https://mitulvaghamshi.github.io
publish_to: none

version: 0.0.1

environment:
  sdk: ^3.11.0
  flutter: ^3.41.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  extra_lints:
    git:
      url: https://github.com/mitulvaghamshi/extra_lints.git
  flutter_test:
    sdk: flutter

flutter:
