name: theme_extension_builder
description: A new Flutter package project.
homepage: https://mitulvaghamshi.github.io
publish_to: none

version: 0.0.1

environment:
  sdk: ^3.11.0
  flutter: ^3.41.1

dependencies:
  analyzer: ^10.0.1
  build: ^4.0.2
  build_config: ^1.1.1
  flutter:
    sdk: flutter
  source_gen: ^4.0.0
  theme_extension:
    path: ../theme_extension

dev_dependencies:
  extra_lints:
    git:
      url: https://github.com/mitulvaghamshi/extra_lints.git
  flutter_test:
    sdk: flutter

flutter:
