name: portfolio
description: Portfolio.
homepage: https://mitulvaghamshi.github.io
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  http: ^1.1.0
  theme_extension:
    path: ../packages/theme_extension
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.6
  extra_lints:
    git:
      url: https://github.com/mitulvaghamshi/extra_lints.git
  theme_extension_builder:
    path: ../packages/theme_extension_builder

flutter:
  uses-material-design: true

  assets:
    - assets/me.webp
    - assets/wes.webp
    - assets/icon.webp
    - assets/repos.json
